name: Build

on:
    push:
        branches:
            - "master"
            - "develop"
    pull_request:
        types: [ready_for_review, synchronize, opened]

jobs:
    linux:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}

            - uses: pnpm/action-setup@v2.0.1
              with:
                  version: 6.20.3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"

            - name: Update System
              run: sudo apt-get update

            - name: Install (Ledger Requirements)
              run: sudo apt-get install libudev-dev libusb-1.0-0-dev

            - name: Install (Yarn)
              run: pnpm install

            - name: Build
              run: pnpm run build:ci

    mac:
        runs-on: macos-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}

            - uses: pnpm/action-setup@v2.0.1
              with:
                  version: 6.20.3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"

            - name: Install
              run: pnpm install

            - name: Build
              run: pnpm run build:ci

    windows:
        runs-on: windows-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}

            - uses: pnpm/action-setup@v2.0.1
              with:
                  version: 6.20.3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"

            - name: Install
              run: pnpm install

            - name: Build
              run: pnpm run build:ci
