name: Draft Artifacts

on:
    push:
        branches:
            - "develop"
    pull_request:
        types: [ready_for_review, synchronize, opened]

jobs:
    linux:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        concurrency:
            group: ${{ github.head_ref }}-draft-linux
            cancel-in-progress: true

        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}

            - uses: pnpm/action-setup@v2.0.1
              with:
                  version: 6.20.3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"

            - name: Update System
              run: sudo apt-get update

            - name: Install (Ledger Requirements)
              run: sudo apt-get install libudev-dev libusb-1.0-0-dev

            - name: Install (Yarn)
              run: pnpm install

            - name: Build
              run: pnpm run build:linux

            - name: Upload .AppImage
              uses: actions/upload-artifact@master
              with:
                  name: payvo-wallet-linux-1.0.0.AppImage
                  path: dist/target/payvo-wallet-linux-x86_64-1.0.0.AppImage

            - name: Upload .tar.gz
              uses: actions/upload-artifact@master
              with:
                  name: payvo-wallet-linux-1.0.0.tar.gz
                  path: dist/target/payvo-wallet-linux-x64-1.0.0.tar.gz

            - name: Upload .deb
              uses: actions/upload-artifact@master
              with:
                  name: payvo-wallet-linux-1.0.0-${{ github.sha }}.deb
                  path: dist/target/payvo-wallet-linux-amd64-1.0.0.deb

    macOS:
        runs-on: macos-latest

        strategy:
            matrix:
                node-version: [14.x]

        concurrency:
            group: ${{ github.head_ref }}-draft-macOS
            cancel-in-progress: true

        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}

            - uses: pnpm/action-setup@v2.0.1
              with:
                  version: 6.20.3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"

            - name: Install (Yarn)
              run: pnpm install

            - name: Prepare for app notarization
              run: |
                  mkdir -p ~/private_keys/
                  echo '${{ secrets.APPLE_API_KEY }}' > ~/private_keys/AuthKey_${{ secrets.APPLE_API_KEY_ID }}.p8

            - name: Build
              run: pnpm run build:mac
              env:
                  APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
                  APPLE_API_KEY_ISSUER_ID: ${{ secrets.APPLE_API_KEY_ISSUER_ID }}
                  CSC_LINK: ${{ secrets.CSC_LINK }}
                  CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}

            - name: Upload .zip
              uses: actions/upload-artifact@master
              with:
                  name: payvo-wallet-mac-1.0.0.zip
                  path: dist/target/payvo-wallet-mac-1.0.0.zip

            - name: Upload .dmg
              uses: actions/upload-artifact@v2
              with:
                  name: payvo-wallet-mac-1.0.0-${{ github.sha }}.dmg
                  path: dist/target/payvo-wallet-mac-1.0.0.dmg

    windows:
        runs-on: windows-latest

        strategy:
            matrix:
                node-version: [14.x]

        concurrency:
            group: ${{ github.head_ref }}-draft-windows
            cancel-in-progress: true

        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}

            - uses: pnpm/action-setup@v2.0.1
              with:
                  version: 6.20.3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"

            - name: Install (Yarn)
              run: pnpm install
              shell: cmd

            - name: Build
              run: pnpm run build:win
              shell: cmd

            - name: Upload .exe
              uses: actions/upload-artifact@v2
              with:
                  name: payvo-wallet-win-1.0.0-${{ github.sha }}.exe
                  path: dist/target/payvo-wallet-win-1.0.0.exe
