name: E2E

on:
    push:
        branches:
            - master
            - develop
            - develop-ledger
    pull_request:
        types: [ready_for_review, synchronize, opened]

jobs:
    build-and-upload:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        concurrency:
            group: ${{ github.head_ref }}-build-and-upload
            cancel-in-progress: true

        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}

            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn cache dir)"

            - name: Cache node modules
              uses: actions/cache@v2
              id: yarn-cache
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: ${{ runner.os }}-yarn-

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Update System
              run: sudo apt-get update

            - name: Install (Ledger Requirements)
              run: sudo apt-get install libudev-dev libusb-1.0-0-dev

            - name: Install (Yarn)
              run: yarn install --ignore-engines --frozen-lockfile

            - name: Build
              run: yarn build:e2e

            - name: Upload Build Artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: build
                  path: ${{ github.workspace }}/build

    vote:
        needs: build-and-upload

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        concurrency:
            group: ${{ github.head_ref }}-e2e-vote
            cancel-in-progress: true

        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}

            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn cache dir)"

            - name: Cache node modules
              uses: actions/cache@v2
              id: yarn-cache
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: ${{ runner.os }}-yarn-

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Update System
              run: sudo apt-get update

            - name: Install (Ledger Requirements)
              run: sudo apt-get install libudev-dev libusb-1.0-0-dev

            - name: Install (Yarn)
              run: yarn install --ignore-engines --frozen-lockfile

            - name: Download Build Artifact
              uses: actions/download-artifact@v2
              with:
                  name: build
                  path: ${{ github.workspace }}/build

            - name: Test
              run: xvfb-run --server-args="-screen 0 1920x1080x16" yarn test:e2e:ci src/domains/vote/cucumber

            - name: Upload Screenshots
              if: ${{ failure() }}
              uses: actions/upload-artifact@v2
              with:
                  name: ${{ github.job }}-screenshots
                  path: ${{ github.workspace }}/screenshots/**/*

    transaction:
        needs: build-and-upload

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        concurrency:
            group: ${{ github.head_ref }}-e2e-transaction
            cancel-in-progress: true

        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}

            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn cache dir)"

            - name: Cache node modules
              uses: actions/cache@v2
              id: yarn-cache
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: ${{ runner.os }}-yarn-

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Update System
              run: sudo apt-get update

            - name: Install (Ledger Requirements)
              run: sudo apt-get install libudev-dev libusb-1.0-0-dev

            - name: Install (Yarn)
              run: yarn install --ignore-engines --frozen-lockfile

            - name: Download Build Artifact
              uses: actions/download-artifact@v2
              with:
                  name: build
                  path: ${{ github.workspace }}/build

            - name: Test
              run: xvfb-run --server-args="-screen 0 1920x1080x16" yarn test:e2e:ci src/domains/transaction/cucumber

            - name: Upload Screenshots
              if: ${{ failure() }}
              uses: actions/upload-artifact@v2
              with:
                  name: ${{ github.job }}-screenshots
                  path: ${{ github.workspace }}/screenshots/**/*

    contact:
        needs: build-and-upload

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        concurrency:
            group: ${{ github.head_ref }}-e2e-contact
            cancel-in-progress: true

        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}

            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn cache dir)"

            - name: Cache node modules
              uses: actions/cache@v2
              id: yarn-cache
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: ${{ runner.os }}-yarn-

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Update System
              run: sudo apt-get update

            - name: Install (Ledger Requirements)
              run: sudo apt-get install libudev-dev libusb-1.0-0-dev

            - name: Install (Yarn)
              run: yarn install --ignore-engines --frozen-lockfile

            - name: Download Build Artifact
              uses: actions/download-artifact@v2
              with:
                  name: build
                  path: ${{ github.workspace }}/build

            - name: Test
              run: xvfb-run --server-args="-screen 0 1920x1200x16" yarn test:e2e:ci src/domains/contact/cucumber

            - name: Upload Screenshots
              if: ${{ failure() }}
              uses: actions/upload-artifact@v2
              with:
                  name: ${{ github.job }}-screenshots
                  path: ${{ github.workspace }}/screenshots/**/*

    plugin:
        needs: build-and-upload

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        concurrency:
            group: ${{ github.head_ref }}-e2e-plugins
            cancel-in-progress: true

        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}

            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn cache dir)"

            - name: Cache node modules
              uses: actions/cache@v2
              id: yarn-cache
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: ${{ runner.os }}-yarn-

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Update System
              run: sudo apt-get update

            - name: Install (Ledger Requirements)
              run: sudo apt-get install libudev-dev libusb-1.0-0-dev

            - name: Install (Yarn)
              run: yarn install --ignore-engines --frozen-lockfile

            - name: Download Build Artifact
              uses: actions/download-artifact@v2
              with:
                  name: build
                  path: ${{ github.workspace }}/build

            - name: Test
              run: xvfb-run --server-args="-screen 0 1920x1080x16" yarn test:e2e:ci src/domains/plugin/cucumber

            - name: Upload Screenshots
              if: ${{ failure() }}
              uses: actions/upload-artifact@v2
              with:
                  name: ${{ github.job }}-screenshots
                  path: ${{ github.workspace }}/screenshots/**/*

    dashboard:
        needs: build-and-upload

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        concurrency:
            group: ${{ github.head_ref }}-e2e-dashboard
            cancel-in-progress: true

        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}

            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn cache dir)"

            - name: Cache node modules
              uses: actions/cache@v2
              id: yarn-cache
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: ${{ runner.os }}-yarn-

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Update System
              run: sudo apt-get update

            - name: Install (Ledger Requirements)
              run: sudo apt-get install libudev-dev libusb-1.0-0-dev

            - name: Install (Yarn)
              run: yarn install --ignore-engines --frozen-lockfile

            - name: Download Build Artifact
              uses: actions/download-artifact@v2
              with:
                  name: build
                  path: ${{ github.workspace }}/build

            - name: Test
              run: xvfb-run --server-args="-screen 0 1920x1080x16" yarn test:e2e:ci src/domains/dashboard/cucumber

            - name: Upload Screenshots
              if: ${{ failure() }}
              uses: actions/upload-artifact@v2
              with:
                  name: ${{ github.job }}-screenshots
                  path: ${{ github.workspace }}/screenshots/**/*

    profile:
        needs: build-and-upload

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        concurrency:
            group: ${{ github.head_ref }}-e2e-profile
            cancel-in-progress: true

        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}

            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn cache dir)"

            - name: Cache node modules
              uses: actions/cache@v2
              id: yarn-cache
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: ${{ runner.os }}-yarn-

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Update System
              run: sudo apt-get update

            - name: Install (Ledger Requirements)
              run: sudo apt-get install libudev-dev libusb-1.0-0-dev

            - name: Install (Yarn)
              run: yarn install --ignore-engines --frozen-lockfile

            - name: Download Build Artifact
              uses: actions/download-artifact@v2
              with:
                  name: build
                  path: ${{ github.workspace }}/build

            - name: Test
              run: xvfb-run --server-args="-screen 0 1920x1080x16" yarn test:e2e:ci src/domains/profile/cucumber

            - name: Upload Screenshots
              if: ${{ failure() }}
              uses: actions/upload-artifact@v2
              with:
                  name: ${{ github.job }}-screenshots
                  path: ${{ github.workspace }}/screenshots/**/*

    news:
        needs: build-and-upload

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        concurrency:
            group: ${{ github.head_ref }}-e2e-news
            cancel-in-progress: true

        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}

            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn cache dir)"

            - name: Cache node modules
              uses: actions/cache@v2
              id: yarn-cache
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: ${{ runner.os }}-yarn-

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Update System
              run: sudo apt-get update

            - name: Install (Ledger Requirements)
              run: sudo apt-get install libudev-dev libusb-1.0-0-dev

            - name: Install (Yarn)
              run: yarn install --ignore-engines --frozen-lockfile

            - name: Download Build Artifact
              uses: actions/download-artifact@v2
              with:
                  name: build
                  path: ${{ github.workspace }}/build

            - name: Test
              run: xvfb-run --server-args="-screen 0 1920x1080x16" yarn test:e2e:ci src/domains/news/cucumber

            - name: Upload Screenshots
              if: ${{ failure() }}
              uses: actions/upload-artifact@v2
              with:
                  name: ${{ github.job }}-screenshots
                  path: ${{ github.workspace }}/screenshots/**/*

    wallet:
        needs: build-and-upload

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        concurrency:
            group: ${{ github.head_ref }}-e2e-wallet
            cancel-in-progress: true

        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}

            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn cache dir)"

            - name: Cache node modules
              uses: actions/cache@v2
              id: yarn-cache
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: ${{ runner.os }}-yarn-

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Update System
              run: sudo apt-get update

            - name: Install (Ledger Requirements)
              run: sudo apt-get install libudev-dev libusb-1.0-0-dev

            - name: Install (Yarn)
              run: yarn install --ignore-engines --frozen-lockfile

            - name: Download Build Artifact
              uses: actions/download-artifact@v2
              with:
                  name: build
                  path: ${{ github.workspace }}/build

            - name: Test
              run: xvfb-run --server-args="-screen 0 1920x1080x16" yarn test:e2e:ci src/domains/wallet/cucumber

            - name: Upload Screenshots
              if: ${{ failure() }}
              uses: actions/upload-artifact@v2
              with:
                  name: ${{ github.job }}-screenshots
                  path: ${{ github.workspace }}/screenshots/**/*

    settings:
        needs: build-and-upload

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        concurrency:
            group: ${{ github.head_ref }}-e2e-settings
            cancel-in-progress: true

        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}

            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn cache dir)"

            - name: Cache node modules
              uses: actions/cache@v2
              id: yarn-cache
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: ${{ runner.os }}-yarn-

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Update System
              run: sudo apt-get update

            - name: Install (Ledger Requirements)
              run: sudo apt-get install libudev-dev libusb-1.0-0-dev

            - name: Install (Yarn)
              run: yarn install --ignore-engines --frozen-lockfile

            - name: Download Build Artifact
              uses: actions/download-artifact@v2
              with:
                  name: build
                  path: ${{ github.workspace }}/build

            - name: Test
              run: xvfb-run --server-args="-screen 0 1920x1080x16" yarn test:e2e:ci src/domains/setting/cucumber

            - name: Upload Screenshots
              if: ${{ failure() }}
              uses: actions/upload-artifact@v2
              with:
                  name: ${{ github.job }}-screenshots
                  path: ${{ github.workspace }}/screenshots/**/*
